### ISSUE TITLE
文件内容修改后，返回的还是老内容

### ISSUE THREAD

**Issue by lldacing** [advence-liz/json-server-router#11]
看效果也自动重启重新打开api页面了，但是返回的内容还是老的

**Comment by lldacing** [comment]
window的原因，我上次提的问题，你修改后，导致缓存中的路径匹配不上了（路径变量用的是/和require.cache中的是\），删缓存没删掉

**Comment by advence-liz** [comment]
搞定了，并且优化了每次保存浏览器都会打开新页面的问题。
