### ISSUE TITLE
Cannot GET /books

### ISSUE THREAD

**Issue by justfunxin** [advence-liz/json-server-router#2]
部署以后只有首页能打开
http://localhost:3000/
`[
    {
        "prefix": "D:/workspace/node/mock/books",
        "routes": {
            "update": {
                "code": 201,
                "message": "succeed",
                "data": true
            },
            "retrieve": {
                "code": 200,
                "message": "succeed",
                "data": true
            },
            "create": {
                "code": 200,
                "message": "succeed",
                "data": true
            },
            "delete": {
                "code": 200,
                "message": "succeed",
                "data": true
            },
            "list": [
                {
                    "id": 0,
                    "name": "book1"
                },
                {
                    "id": 1,
                    "name": "book2"
                },
                {
                    "id": 2,
                    "name": "book3"
                }
            ]
        }
    }
]`
无法访问
http://localhost:3000/books/update  
GET /books/update 404 0.235 ms - 151

**Comment by advence-liz** [comment]
![11563948223_ pic_hd](https://user-images.githubusercontent.com/18550990/61769144-e45a8b80-ae1b-11e9-8189-bfea1cc2813d.jpg)
不好意思看到的有点晚，可以加微信联系我

**Comment by advence-liz** [comment]
感谢反馈问题已经解决了，因为我们这里项目使用的接口名字比较长，因此没有mock数据直接在跟目录下的场景所有没有测试到这个问题。
