### ISSUE TITLE
用不了，一直是404

### ISSUE THREAD

**Issue by bookser** [advence-liz/json-server-router#6]
通过npm安装2.3.0，启动成功后，点击都是404，无法访问数据
需要怎么操作修改，谢谢

**Comment by advence-liz** [comment]
![image](https://user-images.githubusercontent.com/18550990/80351808-8163bc80-88a5-11ea-8528-6ec7d12090c8.png)
有在example目录下运行吗？如果解决不了加微信联系我  advence-liz

**Comment by advence-liz** [comment]
> 通过npm安装2.3.0，启动成功后，点击都是404，无法访问数据
> 需要怎么操作修改，谢谢

有测试当前的工程下的 example 嘛？ https://github.com/advence-liz/json-server-router/tree/master/example

如果还是不行，可以直接微信联系我 微信  advence-liz
