### ISSUE TITLE
window中文件名的路径取的不对

### ISSUE THREAD

**Issue by lldacing** [advence-liz/json-server-router#8]
windows中的分隔符是反斜杠，所以启动后映射的文件名是反斜杠\books/update，导致访问不到/books/update
试了下把index.js中
const prefix = filePath
        .replace(/\.(js|json)$/, '')
        .replace(/\/index$/, '')
        .replace(this.isFile ? path.parse(root).dir : root, '')
改成
const prefix = filePath
        .replace(/\.(js|json)$/, '')
        .replace(/\/index$/, '')
        .replace(this.isFile ? path.parse(root).dir : root, '').replace(/\\\\/,'/')可以访问

另外，问下，路径映射能支持类似正则占位符的映射吗，如“/test/([0-9]+)“映射成“/$1“，访问/test/123456映射到/123456

**Comment by advence-liz** [comment]
忙于搬砖，不好意思看到有点晚，之前没有注意过window，之后适配一下。

另一个需求之后会集成 rewriter 应该就能满足需求 https://github.com/typicode/json-server#rewriter-example

**Comment by advence-liz** [comment]
> windows中的分隔符是反斜杠，所以启动后映射的文件名是反斜杠\books/update，导致访问不到/books/update
> 试了下把index.js中
> const prefix = filePath
> .replace(/.(js|json)$/, '')
> .replace(//index$/, '')
> .replace(this.isFile ? path.parse(root).dir : root, '')
> 改成
> const prefix = filePath
> .replace(/.(js|json)$/, '')
> .replace(//index$/, '')
> .replace(this.isFile ? path.parse(root).dir : root, '').replace(/\\/,'/')可以访问
> 
> 另外，问下，路径映射能支持类似正则占位符的映射吗，如“/test/([0-9]+)“映射成“/$1“，访问/test/123456映射到/123456

忙于搬砖，不好意思看到有点晚，之前没有注意过window，之后适配一下。

另一个需求之后会集成 rewriter 应该就能满足需求 https://github.com/typicode/json-server#re

**Comment by advence-liz** [comment]
问题解决了， rewrite 功能也加好了，详见 https://github.com/advence-liz/json-server-router#add-coustom-routes-rewrite
![image](https://user-images.githubusercontent.com/18550990/98132982-ff112080-1ef7-11eb-9edb-f3998862e230.png)

**Comment by lldacing** [comment]
> 问题解决了， rewrite 功能也加好了，详见 https://github.com/advence-liz/json-server-router#add-coustom-routes-rewrite
> 
> ![image](https://user-images.githubusercontent.com/18550990/98132982-ff112080-1ef7-11eb-9edb-f3998862e230.png)
> 
> 

一直忙没空验证，最近有需要用了，今天试了下还是不行，感觉没生效，直接运行你工程里你的例子也不行，不知道怎么回事

**Comment by lldacing** [comment]
> > 问题解决了， rewrite 功能也加好了，详见 https://github.com/advence-liz/json-server-router#add-coustom-routes-rewrite
> > 
> > ![image](https://user-images.githubusercontent.com/18550990/98132982-ff112080-1ef7-11eb-9edb-f3998862e230.png)
> > 
> > 
> 
> 一直忙没空验证，最近有需要用了，今天试了下还是不行，感觉没生效，直接运行你工程里你的例子也不行，不知道怎么回事

找到原因了，cli/server.js里面new JsonServerRouter时没传routes
